---
# tasks file for munin.

- name: OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_os_family }}_family.yml"
      paths:
        - "../vars/"
  tags:
    - munin
    - setup
    - service
    - config

# Debian(setup) specific tasks.
- include: setup-Debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - munin
    - setup

# RedHat(setup) specific tasks.
- include: setup-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - munin
    - setup

# Common configuration tasks.
- include: config.yml
  tags:
    - munin
    - config

# Common service tasks.
- include: service.yml
  when: munin_role_node == true
  tags:
   - munin
   - service

# Integration with external services.
- include: external.yml
  tags:
   - munin
   - external

